version: "3"
 
services:
  scouting-client:
    container_name: "scouting-client"
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    env_file:
      - .env
    expose:
      - 3000
      - 5000
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./client:/app

  couchdb:
    container_name: "scouting-server"
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: ./Dockerfile
    expose:
      - 5984
    ports:
      - "5984:5984"
    env_file:
      - .env
    environment:
      - COUCHDB_HOST=couchdb
      - COUCHDB_PORT=5984
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./server/db.local.ini:/opt/couchdb/etc/local.ini
      - ./server/data:/opt/couchdb/data
