version: "3"
 
services:
  scouting-client:
    container_name: "scouting-client"
    restart: unless-stopped
    env_file:
      - .env
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    expose:
      - 80
    ports:
      - "80:80/tcp"
  couchdb:
    container_name: "scouting-server"
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./server
      dockerfile: ./Dockerfile
    expose:
      - 5984
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_HOST=couchdb
      - COUCHDB_PORT=5984
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./server/db.local.ini:/opt/couchdb/etc/local.ini
      - ./server/data:/opt/couchdb/data
